// frontend/src/pages/Login.jsx
import { useState } from 'preact/hooks'
import { api, setAuth } from '../utils/api.js'

export default function Login({ onLogin }) {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!username || !password) {
      setError('请输入用户名和密码')
      return
    }
    setError('')
    setLoading(true)
    try {
      const res = await api.login(username.trim(), password)
      setAuth(res.token, res.user)
      onLogin(res.user, res.token)
    } catch (err) {
      setError(err.message || '登录失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="login-page">
      <div className="login-box">
        <h1>幼儿园晨检记录系统</h1>
        <p className="subtitle">节点超时追踪 · 角色权限管理</p>
        {error && <div className="alert alert-error">{error}</div>}
        <form onSubmit={handleSubmit}>
          <div className="form-item">
            <label>用户名</label>
            <input
              type="text"
              value={username}
              onInput={(e) => setUsername(e.target.value)}
              placeholder="请输入用户名"
              autoComplete="username"
            />
          </div>
          <div className="form-item">
            <label>密码</label>
            <input
              type="password"
              value={password}
              onInput={(e) => setPassword(e.target.value)}
              placeholder="请输入密码"
              autoComplete="current-password"
            />
          </div>
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? '登录中...' : '登 录'}
          </button>
        </form>
        <div className="account-hints">
          <div>测试账号：</div>
          <div>晨检登记员：registrar1 / 123456</div>
          <div>晨检审核主管：auditor1 / 123456</div>
          <div>幼儿园复核负责人：reviewer1 / 123456</div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/login.tsx
import { createSignal, Component } from "solid-js";
import { useNavigate, Navigate } from "@solidjs/router";
import { useApp } from "../lib/store";
import { api } from "../lib/api";

const Login: Component = () => {
  const app = useApp();
  const navigate = useNavigate();
  const [username, setUsername] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal("");

  if (app.token()) {
    return <Navigate href="/bills" />;
  }

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const response = await api.login(username(), password());
      app.setToken(response.access_token);
      app.setUser(response.user);
      navigate("/bills");
    } catch (err: any) {
      setError(err.message || "登录失败");
    } finally {
      setLoading(false);
    }
  };

  const fillCredentials = (u: string, p: string) => {
    setUsername(u);
    setPassword(p);
  };

  return (
    <div class="login-page">
      <div class="login-card">
        <h2>⚡ 能耗账单管理系统</h2>
        <p class="subtitle">登录后开始处理能耗账单流程</p>

        {error() && <div class="alert alert-error">{error()}</div>}

        <form onSubmit={handleSubmit}>
          <div class="form-group">
            <label>用户名</label>
            <input
              type="text"
              value={username()}
              onInput={(e) => setUsername(e.target.value)}
              placeholder="请输入用户名"
              required
            />
          </div>
          <div class="form-group">
            <label>密码</label>
            <input
              type="password"
              value={password()}
              onInput={(e) => setPassword(e.target.value)}
              placeholder="请输入密码"
              required
            />
          </div>
          <button
            type="submit"
            class="btn btn-primary"
            style={{ width: "100%" }}
            disabled={loading()}
          >
            {loading() ? <span class="spinner"></span> : "登 录"}
          </button>
        </form>

        <div class="test-accounts">
          <h4>测试账号（点击快速填充）:</h4>
          <div class="test-account-item" onClick={() => fillCredentials("registrar", "123456")}>
            <span>registrar / 123456</span>
            <span class="role">能耗账登记员</span>
          </div>
          <div class="test-account-item" onClick={() => fillCredentials("auditor", "123456")}>
            <span>auditor / 123456</span>
            <span class="role">能耗账审核主管</span>
          </div>
          <div class="test-account-item" onClick={() => fillCredentials("property", "123456")}>
            <span>property / 123456</span>
            <span class="role">产业园物业复核负责人</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
