// frontend/components/StatusBadge.tsx
import { STATUS_MAP, STATUS_COLORS } from "../utils/types.ts";

interface StatusBadgeProps {
  status: string;
}

export function StatusBadge({ status }: StatusBadgeProps) {
  const label = STATUS_MAP[status] || status;
  const color = STATUS_COLORS[status] || "bg-gray-100 text-gray-800";
  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${color}`}>
      {label}
    </span>
  );
}

// frontend/src/components/StatusBadge.tsx
import { component$ } from "@builder.io/qwik";
import type { InspectionStatus, RiskLevel } from "~/types";
import { statusLabels, statusColors, riskLabels, riskColors } from "~/utils/format";

interface StatusBadgeProps {
  status: InspectionStatus;
}

export const StatusBadge = component$<StatusBadgeProps>(({ status }) => {
  return (
    <span
      class={`px-2 py-1 rounded-full text-xs font-medium ${statusColors[status]}`}
    >
      {statusLabels[status]}
    </span>
  );
});

interface RiskBadgeProps {
  level: RiskLevel;
  showIcon?: boolean;
}

export const RiskBadge = component$<RiskBadgeProps>(
  ({ level, showIcon = false }) => {
    return (
      <span
        class={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${riskColors[level]}`}
      >
        {showIcon && level === "HIGH" && <span>⚠️</span>}
        {riskLabels[level]}
      </span>
    );
  }
);
