// frontend/src/components/StatusBadge.tsx
import { component$ } from "@builder.io/qwik";
import type { InspectionStatus, RiskLevel } from "~/types";
import { statusLabels, statusColors, riskLabels, riskColors } from "~/utils/format";

interface StatusBadgeProps {
  status: InspectionStatus;
}

export const StatusBadge = component$<StatusBadgeProps>(({ status }) => {
  return (
    <span
      class={`px-2 py-1 rounded-full text-xs font-medium ${statusColors[status]}`}
    >
      {statusLabels[status]}
    </span>
  );
});

interface RiskBadgeProps {
  level: RiskLevel;
  showIcon?: boolean;
}

export const RiskBadge = component$<RiskBadgeProps>(
  ({ level, showIcon = false }) => {
    return (
      <span
        class={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${riskColors[level]}`}
      >
        {showIcon && level === "HIGH" && <span>⚠️</span>}
        {riskLabels[level]}
      </span>
    );
  }
);

// frontend/app/components/StatusBadge.tsx
import {
  CONFIRMATION_ORDER_STATUS_LABELS,
  CONFIRMATION_ORDER_STATUS_COLORS,
  PAYMENT_VERIFICATION_STATUS_LABELS,
  PAYMENT_VERIFICATION_STATUS_COLORS,
  type ConfirmationOrderStatus,
  type PaymentVerificationStatus,
} from '~/lib/constants';

interface StatusBadgeProps {
  status: ConfirmationOrderStatus | PaymentVerificationStatus;
  type?: 'confirmation' | 'payment';
}

export function StatusBadge({ status, type = 'confirmation' }: StatusBadgeProps) {
  const isConfirmation = type === 'confirmation';
  const labels = isConfirmation
    ? CONFIRMATION_ORDER_STATUS_LABELS
    : PAYMENT_VERIFICATION_STATUS_LABELS;
  const colors = isConfirmation
    ? CONFIRMATION_ORDER_STATUS_COLORS
    : PAYMENT_VERIFICATION_STATUS_COLORS;

  const label = (labels as Record<string, string>)[status] || status;
  const color = (colors as Record<string, string>)[status] || 'bg-gray-100 text-gray-800';

  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${color}`}>
      {label}
    </span>
  );
}
