// frontend/src/routes/plans/[id]/+page.svelte
<script>
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';
	import { auth, statusNames, statusColors, evidenceTypeNames, roleNames, operationNames, operationColors } from '$lib/store';

	let planId = $page.params.id ?? '';
	let planDetail = null;
	let loading = true;
	let error = '';
	let actionLoading = false;
	let showRejectModal = false;
	let rejectReason = '';
	let showRemarkModal = false;
	let remarkText = '';
	let currentAction = '';

	$effect(() => {
		planId = $page.params.id ?? '';
		if (planId && $auth.token) {
			loadDetail();
		}
	});

	async function loadDetail() {
		loading = true;
		error = '';
		try {
			const data = await api.getPlan(planId);
			planDetail = data;
		} catch (e) {
			error = e.message;
		} finally {
			loading = false;
		}
	}

	function canSubmit() {
		if (!$auth.user || !planDetail) return false;
		return $auth.user.role === 'registrar' &&
			planDetail.plan.created_by === $auth.user.id &&
			(planDetail.plan.status === 'draft' || planDetail.plan.status === 'audit_rejected');
	}

	function canEdit() {
		if (!$auth.user || !planDetail) return false;
		return $auth.user.role === 'registrar' &&
			planDetail.plan.created_by === $auth.user.id &&
			(planDetail.plan.status === 'draft' || planDetail.plan.status === 'audit_rejected');
	}

	function canApprove() {
		if (!$auth.user || !planDetail) return false;
		return $auth.user.role === 'auditor' &&
			(planDetail.plan.status === 'pending_audit' || planDetail.plan.status === 'review_rejected');
	}

	function canReject() {
		if (!$auth.user || !planDetail) return false;
		return $auth.user.role === 'auditor' &&
			(planDetail.plan.status === 'pending_audit' || planDetail.plan.status === 'review_rejected');
	}

	function canReview() {
		if (!$auth.user || !planDetail) return false;
		return $auth.user.role === 'reviewer' && planDetail.plan.status === 'pending_review';
	}

	function canArchive() {
		if (!$auth.user || !planDetail) return false;
		return $auth.user.role === 'reviewer' && planDetail.plan.status === 'review_approved';
	}

	async function handleSubmit() {
		actionLoading = true;
		error = '';
		try {
			await api.submitPlan(planId, planDetail.plan.version);
			await loadDetail();
		} catch (e) {
			error = e.message;
		} finally {
			actionLoading = false;
		}
	}

	function openApproveModal() {
		currentAction = 'approve';
		remarkText = '';
		showRemarkModal = true;
	}

	async function handleApprove() {
		actionLoading = true;
		error = '';
		try {
			await api.approvePlan(planId, {
				version: planDetail.plan.version,
				remark: remarkText || null
			});

			await api.reviewPlan(planId, {
				version: planDetail.plan.version + 1,
				remark: '自动送复核'
			}).catch(() => {});

			await loadDetail();
			showRemarkModal = false;
		} catch (e) {
			error = e.message;
		} finally {
			actionLoading = false;
		}
	}

	function openRejectModal() {
		rejectReason = '';
		showRejectModal = true;
	}

	async function handleReject() {
		if (!rejectReason.trim()) {
			error = '请输入驳回原因';
			return;
		}
		actionLoading = true;
		error = '';
		try {
			await api.rejectPlan(planId, {
				version: planDetail.plan.version,
				reason: rejectReason
			});
			await loadDetail();
			showRejectModal = false;
		} catch (e) {
			error = e.message;
		} finally {
			actionLoading = false;
		}
	}

	function openReviewModal() {
		currentAction = 'review';
		remarkText = '';
		showRemarkModal = true;
	}

	async function handleReview() {
		actionLoading = true;
		error = '';
		try {
			await api.reviewPlan(planId, {
				version: planDetail.plan.version,
				remark: remarkText || null
			});
			await loadDetail();
			showRemarkModal = false;
		} catch (e) {
			error = e.message;
		} finally {
			actionLoading = false;
		}
	}

	async function handleArchive() {
		if (!confirm('确认归档此计划单吗？归档后不可修改。')) return;
		actionLoading = true;
		error = '';
		try {
			await api.archivePlan(planId, planDetail.plan.version);
			await loadDetail();
		} catch (e) {
			error = e.message;
		} finally {
			actionLoading = false;
		}
	}

	function formatDate(dateStr) {
		if (!dateStr) return '-';
		try {
			const d = new Date(dateStr);
			return d.toLocaleString('zh-CN', {
				year: 'numeric',
				month: '2-digit',
				day: '2-digit',
				hour: '2-digit',
				minute: '2-digit',
				second: '2-digit'
			});
		} catch {
			return dateStr;
		}
	}

	function goBack() {
		goto('/dashboard?refresh=1');
	}

	function getTotalBudget() {
		if (!planDetail) return 0;
		return planDetail.budgets.reduce((sum, b) => sum + b.amount, 0);
	}

	onMount(() => {
		if (!$auth.token) {
			goto('/');
		}
	});
</script>

<div class="detail-page">
	<div class="page-header">
		<button class="back-btn" on:click={goBack}>← 返回</button>
		<h1>媒介计划单详情</h1>
	</div>

	{#if loading}
		<div class="loading">加载中...</div>
	{:else if error && !planDetail}
		<div class="error-state">
			<div class="error-icon">❌</div>
			<h3>加载失败</h3>
			<p>{error}</p>
			<button on:click={loadDetail}>重试</button>
		</div>
	{:else if planDetail}
		<div class="detail-container">
			<div class="main-section">
				<div class="info-card">
					<div class="card-header">
						<h2>基本信息</h2>
						<span
							class="status-badge large"
							style="background: {statusColors[planDetail.plan.status]}20; color: {statusColors[planDetail.plan.status]}"
						>
							{statusNames[planDetail.plan.status]}
						</span>
					</div>

					<div class="info-grid">
						<div class="info-item">
							<label>计划单编号</label>
							<span class="value mono">{planDetail.plan.plan_no}</span>
						</div>
						<div class="info-item">
							<label>当前版本</label>
							<span class="value">v{planDetail.plan.version}</span>
						</div>
						<div class="info-item full">
							<label>计划标题</label>
							<span class="value">{planDetail.plan.title}</span>
						</div>
						<div class="info-item">
							<label>客户名称</label>
							<span class="value">{planDetail.plan.client_name}</span>
						</div>
						<div class="info-item">
							<label>创建人</label>
							<span class="value">{planDetail.created_by_name}</span>
						</div>
						<div class="info-item">
							<label>创建时间</label>
							<span class="value">{formatDate(planDetail.plan.created_at)}</span>
						</div>
						<div class="info-item">
							<label>更新时间</label>
							<span class="value">{formatDate(planDetail.plan.updated_at)}</span>
						</div>
						<div class="info-item full">
							<label>备注</label>
							<span class="value">{planDetail.plan.remark || '无'}</span>
						</div>
					</div>

					{#if planDetail.plan.reject_reason}
						<div class="reject-reason">
							<div class="reason-label">⚠️ 驳回原因</div>
							<div class="reason-text">{planDetail.plan.reject_reason}</div>
						</div>
					{/if}
				</div>

				<div class="info-card">
					<div class="card-header">
						<h2>📊 媒介排期</h2>
						<span class="count-badge">{planDetail.schedules.length} 项</span>
					</div>
					<div class="schedule-table">
						<table>
							<thead>
								<tr>
									<th>媒体名称</th>
									<th>广告位置</th>
									<th>开始日期</th>
									<th>结束日期</th>
									<th>投放频次</th>
								</tr>
							</thead>
							<tbody>
								{#each planDetail.schedules as sched (sched.id)}
									<tr>
										<td>{sched.media_name}</td>
										<td>{sched.ad_position}</td>
										<td>{sched.start_date}</td>
										<td>{sched.end_date}</td>
										<td>{sched.frequency}</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</div>

				<div class="info-card">
					<div class="card-header">
						<h2>💰 预算明细</h2>
						<span class="total-budget">总计: ¥{getTotalBudget().toLocaleString()}</span>
					</div>
					<div class="budget-table">
						<table>
							<thead>
								<tr>
									<th>费用项目</th>
									<th>类别</th>
									<th class="amount-col">金额</th>
								</tr>
							</thead>
							<tbody>
								{#each planDetail.budgets as budget (budget.id)}
									<tr>
										<td>{budget.item_name}</td>
										<td><span class="category-tag">{budget.category}</span></td>
										<td class="amount-col">¥{budget.amount.toLocaleString()}</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</div>

				<div class="info-card">
					<div class="card-header">
						<h2>📎 证据材料</h2>
						<span class="count-badge">{planDetail.evidences.length} 份</span>
					</div>
					{#if planDetail.evidences.length === 0}
						<div class="empty-evidence">
							<span class="warning-icon">⚠️</span>
							<span>暂无证据材料，提交前请上传相关证据</span>
						</div>
					{:else}
						<div class="evidence-grid">
							{#each planDetail.evidences as ev (ev.id)}
								<div class="evidence-card">
									<div class="ev-icon">📄</div>
									<div class="ev-info">
										<div class="ev-name">{ev.name}</div>
										<div class="ev-type">{evidenceTypeNames[ev.evidence_type] || ev.evidence_type}</div>
										<div class="ev-time">上传于 {formatDate(ev.uploaded_at)}</div>
									</div>
								</div>
							{/each}
						</div>
					{/if}
				</div>

				<div class="info-card">
					<div class="card-header">
						<h2>📋 办理记录</h2>
						<span class="count-badge">{planDetail.operation_logs.length} 条</span>
					</div>
					<div class="audit-timeline">
						{#each planDetail.operation_logs as log (log.id)}
							<div class="audit-item">
								<div
									class="audit-dot"
									style="background: {operationColors[log.operation] || '#94a3b8'}"
								></div>
								<div class="audit-content">
									<div class="audit-header">
										<span class="audit-op" style="color: {operationColors[log.operation] || '#64748b'}">
											{operationNames[log.operation] || log.operation}
										</span>
										<span class="audit-operator">{log.operator_name}</span>
									</div>
									<div class="audit-status">
										{#if log.old_status && log.new_status && log.old_status !== log.new_status}
											<span class="status-old">{statusNames[log.old_status] || log.old_status}</span>
											<span class="status-arrow">→</span>
											<span class="status-new">{statusNames[log.new_status] || log.new_status}</span>
										{/if}
										{#if log.old_status && log.new_status && log.old_status === log.new_status}
											<span class="status-same">状态未变更</span>
										{/if}
									</div>
									{#if log.remark}
										<div class="audit-remark">{log.remark}</div>
									{/if}
									<div class="audit-time">{formatDate(log.created_at)}</div>
								</div>
							</div>
						{:else}
							<div class="empty-log">暂无办理记录</div>
						{/each}
					</div>
				</div>
			</div>

			<div class="side-section">
				<div class="action-card">
					<h3>办理操作</h3>

					{#if error}
						<div class="error-alert">
							<strong>操作失败</strong>
							<p>{error}</p>
						</div>
					{/if}

					<div class="action-buttons">
						{#if canSubmit()}
							<button class="action-btn primary" on:click={handleSubmit} disabled={actionLoading}>
								{actionLoading ? '提交中...' : '📤 提交审核'}
							</button>
						{/if}

						{#if canApprove()}
							<button class="action-btn success" on:click={openApproveModal} disabled={actionLoading}>
								✅ 审核通过
							</button>
						{/if}

						{#if canReject()}
							<button class="action-btn danger" on:click={openRejectModal} disabled={actionLoading}>
								❌ 审核驳回
							</button>
						{/if}

						{#if canReview()}
							<button class="action-btn primary" on:click={openReviewModal} disabled={actionLoading}>
								📝 复核通过
							</button>
						{/if}

						{#if canArchive()}
							<button class="action-btn secondary" on:click={handleArchive} disabled={actionLoading}>
								📦 归档
							</button>
						{/if}

						{#if !canSubmit() && !canApprove() && !canReject() && !canReview() && !canArchive()}
							<div class="no-action">
								<p>当前状态下您没有可执行的操作</p>
								<p class="hint">当前角色: {roleNames[$auth.user?.role]}</p>
							</div>
						{/if}
					</div>

					<div class="version-hint">
						<div class="hint-title">💡 提示</div>
						<ul>
							<li>每次操作会自动递增版本号</li>
							<li>如果版本不匹配请刷新页面</li>
							<li>提交前请确保已上传证据材料</li>
						</ul>
					</div>
				</div>

				<div class="timeline-card">
					<h3>流程节点</h3>
					<div class="timeline">
						<div class="timeline-item done">
							<div class="timeline-dot"></div>
							<div class="timeline-content">
								<div class="timeline-title">创建草稿</div>
								<div class="timeline-time">{formatDate(planDetail.plan.created_at)}</div>
							</div>
						</div>

						<div class={`timeline-item ${planDetail.plan.submitted_at ? 'done' : ''}`}>
							<div class="timeline-dot"></div>
							<div class="timeline-content">
								<div class="timeline-title">提交审核</div>
								<div class="timeline-time">{planDetail.plan.submitted_at ? formatDate(planDetail.plan.submitted_at) : '待处理'}</div>
							</div>
						</div>

						<div class={`timeline-item ${planDetail.plan.approved_at ? 'done' : ''}`}>
							<div class="timeline-dot"></div>
							<div class="timeline-content">
								<div class="timeline-title">主管审核</div>
								<div class="timeline-time">{planDetail.plan.approved_at ? formatDate(planDetail.plan.approved_at) : '待处理'}</div>
							</div>
						</div>

						<div class={`timeline-item ${planDetail.plan.reviewed_at ? 'done' : ''}`}>
							<div class="timeline-dot"></div>
							<div class="timeline-content">
								<div class="timeline-title">代理复核</div>
								<div class="timeline-time">{planDetail.plan.reviewed_at ? formatDate(planDetail.plan.reviewed_at) : '待处理'}</div>
							</div>
						</div>

						<div class={`timeline-item ${planDetail.plan.archived_at ? 'done' : ''}`}>
							<div class="timeline-dot"></div>
							<div class="timeline-content">
								<div class="timeline-title">归档完成</div>
								<div class="timeline-time">{planDetail.plan.archived_at ? formatDate(planDetail.plan.archived_at) : '待处理'}</div>
							</div>
						</div>
				 </div>
				</div>
			</div>
		</div>
	{/if}

	{#if showRejectModal}
		<div class="modal-overlay" on:click={() => { showRejectModal = false; }}>
			<div class="modal" on:click|stopPropagation>
				<div class="modal-header">
					<h3>审核驳回</h3>
					<button class="close-btn" on:click={() => { showRejectModal = false; }}>✕</button>
				</div>
				<div class="modal-body">
					<p>请填写驳回原因，登记员将收到驳回通知并进行修改。</p>
					<div class="form-group">
						<label>驳回原因</label>
						<textarea bind:value={rejectReason} rows="4" placeholder="请详细说明驳回原因..."></textarea>
					</div>
					{#if error}
						<div class="error-message">{error}</div>
					{/if}
				</div>
				<div class="modal-footer">
					<button class="btn secondary" on:click={() => { showRejectModal = false; }}>取消</button>
					<button class="btn danger" on:click={handleReject} disabled={actionLoading}>
						{actionLoading ? '处理中...' : '确认驳回'}
					</button>
				</div>
			</div>
		</div>
	{/if}

	{#if showRemarkModal}
		<div class="modal-overlay" on:click={() => { showRemarkModal = false; }}>
			<div class="modal" on:click|stopPropagation>
				<div class="modal-header">
					<h3>{currentAction === 'approve' ? '审核通过' : '复核通过'}</h3>
					<button class="close-btn" on:click={() => { showRemarkModal = false; }}>✕</button>
				</div>
				<div class="modal-body">
					<p>确认通过此计划单？</p>
					<div class="form-group">
						<label>备注（可选）</label>
						<textarea bind:value={remarkText} rows="3" placeholder="请输入备注信息..."></textarea>
					</div>
					{#if error}
						<div class="error-message">{error}</div>
					{/if}
				</div>
				<div class="modal-footer">
					<button class="btn secondary" on:click={() => { showRemarkModal = false; }}>取消</button>
					<button class="btn primary" on:click={currentAction === 'approve' ? handleApprove : handleReview} disabled={actionLoading}>
						{actionLoading ? '处理中...' : '确认通过'}
					</button>
				</div>
			</div>
		</div>
	{/if}
</div>

<style>
	.detail-page {
		max-width: 1200px;
		margin: 0 auto;
	}

	.page-header {
		display: flex;
		align-items: center;
		gap: 16px;
		margin-bottom: 20px;
	}

	.back-btn {
		padding: 8px 16px;
		background: white;
		border: 1px solid #cbd5e1;
		border-radius: 8px;
		cursor: pointer;
		font-size: 14px;
	}

	.back-btn:hover {
		background: #f8fafc;
	}

	.page-header h1 {
		margin: 0;
		font-size: 22px;
		color: #1e293b;
	}

	.loading {
		text-align: center;
		padding: 60px;
		color: #64748b;
	}

	.error-state {
		text-align: center;
		padding: 60px;
	}

	.error-icon {
		font-size: 48px;
		margin-bottom: 16px;
	}

	.detail-container {
		display: flex;
		gap: 20px;
	}

	.main-section {
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.side-section {
		width: 320px;
		flex-shrink: 0;
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.info-card {
		background: white;
		border-radius: 12px;
		padding: 20px;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
	}

	.card-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 16px;
		padding-bottom: 12px;
		border-bottom: 1px solid #e2e8f0;
	}

	.card-header h2 {
		margin: 0;
		font-size: 16px;
		color: #1e293b;
	}

	.status-badge.large {
		padding: 6px 12px;
		font-size: 13px;
		border-radius: 6px;
		font-weight: 500;
	}

	.count-badge {
		background: #f1f5f9;
		padding: 4px 10px;
		border-radius: 12px;
		font-size: 12px;
		color: #64748b;
	}

	.total-budget {
		font-size: 15px;
		font-weight: 600;
		color: #059669;
	}

	.info-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 16px;
	}

	.info-item.full {
		grid-column: 1 / -1;
	}

	.info-item label {
		display: block;
		font-size: 12px;
		color: #94a3b8;
		margin-bottom: 4px;
	}

	.info-item .value {
		font-size: 14px;
		color: #334155;
	}

	.info-item .value.mono {
		font-family: monospace;
	}

	.reject-reason {
		margin-top: 16px;
		padding: 12px 16px;
		background: #fef2f2;
		border: 1px solid #fecaca;
		border-radius: 8px;
	}

	.reason-label {
		font-size: 13px;
		font-weight: 500;
		color: #dc2626;
		margin-bottom: 4px;
	}

	.reason-text {
		font-size: 14px;
		color: #991b1b;
	}

	table {
		width: 100%;
		border-collapse: collapse;
	}

	th, td {
		text-align: left;
		padding: 10px 12px;
		border-bottom: 1px solid #f1f5f9;
		font-size: 13px;
	}

	th {
		background: #f8fafc;
		font-weight: 500;
		color: #64748b;
		font-size: 12px;
	}

	.amount-col {
		text-align: right;
	}

	.category-tag {
		display: inline-block;
		padding: 2px 8px;
		background: #eff6ff;
		color: #2563eb;
		border-radius: 4px;
		font-size: 11px;
	}

	.empty-evidence {
		padding: 20px;
		text-align: center;
		background: #fffbeb;
		border: 1px dashed #fcd34d;
		border-radius: 8px;
		color: #92400e;
		font-size: 13px;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 8px;
	}

	.warning-icon {
		font-size: 18px;
	}

	.evidence-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
		gap: 12px;
	}

	.evidence-card {
		display: flex;
		gap: 12px;
		padding: 12px;
		background: #f8fafc;
		border-radius: 8px;
		align-items: flex-start;
	}

	.ev-icon {
		font-size: 28px;
		flex-shrink: 0;
	}

	.ev-info {
		flex: 1;
		min-width: 0;
	}

	.ev-name {
		font-size: 13px;
		font-weight: 500;
		color: #1e293b;
		margin-bottom: 2px;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.ev-type {
		font-size: 12px;
		color: #64748b;
		margin-bottom: 2px;
	}

	.ev-time {
		font-size: 11px;
		color: #94a3b8;
	}

	.action-card {
		background: white;
		border-radius: 12px;
		padding: 20px;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
	}

	.action-card h3 {
		margin: 0 0 16px 0;
		font-size: 16px;
		color: #1e293b;
	}

	.action-buttons {
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	.action-btn {
		width: 100%;
		padding: 12px;
		border: none;
		border-radius: 8px;
		cursor: pointer;
		font-size: 14px;
		font-weight: 500;
		transition: all 0.2s;
	}

	.action-btn.primary {
		background: #2563eb;
		color: white;
	}

	.action-btn.success {
		background: #10b981;
		color: white;
	}

	.action-btn.danger {
		background: #ef4444;
		color: white;
	}

	.action-btn.secondary {
		background: #f1f5f9;
		color: #475569;
	}

	.action-btn:hover:not(:disabled) {
		transform: translateY(-1px);
		box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
	}

	.action-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.no-action {
		text-align: center;
		padding: 20px 0;
		color: #94a3b8;
	}

	.no-action p {
		margin: 4px 0;
		font-size: 13px;
	}

	.no-action .hint {
		font-size: 12px;
		color: #cbd5e1;
	}

	.error-alert {
		background: #fef2f2;
		border: 1px solid #fecaca;
		border-radius: 8px;
		padding: 12px;
		margin-bottom: 16px;
	}

	.error-alert strong {
		color: #dc2626;
		font-size: 13px;
	}

	.error-alert p {
		margin: 4px 0 0 0;
		font-size: 12px;
		color: #991b1b;
	}

	.version-hint {
		margin-top: 20px;
		padding: 12px;
		background: #f8fafc;
		border-radius: 8px;
	}

	.hint-title {
		font-size: 13px;
		font-weight: 500;
		color: #475569;
		margin-bottom: 8px;
	}

	.version-hint ul {
		margin: 0;
		padding-left: 18px;
	}

	.version-hint li {
		font-size: 12px;
		color: #64748b;
		margin-bottom: 4px;
	}

	.timeline-card {
		background: white;
		border-radius: 12px;
		padding: 20px;
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
	}

	.timeline-card h3 {
		margin: 0 0 16px 0;
		font-size: 16px;
		color: #1e293b;
	}

	.timeline {
		position: relative;
	}

	.timeline-item {
		display: flex;
		gap: 12px;
		padding-bottom: 20px;
		position: relative;
	}

	.timeline-item:not(:last-child)::after {
		content: '';
		position: absolute;
		left: 7px;
		top: 20px;
		bottom: 0;
		width: 2px;
		background: #e2e8f0;
	}

	.timeline-item.done:not(:last-child)::after {
		background: #22c55e;
	}

	.timeline-dot {
		width: 16px;
		height: 16px;
		border-radius: 50%;
		background: #cbd5e1;
		flex-shrink: 0;
		margin-top: 2px;
	}

	.timeline-item.done .timeline-dot {
		background: #22c55e;
	}

	.timeline-content {
		flex: 1;
	}

	.timeline-title {
		font-size: 13px;
		font-weight: 500;
		color: #334155;
		margin-bottom: 2px;
	}

	.timeline-item.done .timeline-title {
		color: #166534;
	}

	.timeline-time {
		font-size: 11px;
		color: #94a3b8;
	}

	.modal-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
	}

	.modal {
		background: white;
		border-radius: 12px;
		width: 100%;
		max-width: 440px;
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
	}

	.modal-header {
		padding: 16px 20px;
		border-bottom: 1px solid #e2e8f0;
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.modal-header h3 {
		margin: 0;
		font-size: 16px;
		color: #1e293b;
	}

	.close-btn {
		background: none;
		border: none;
		font-size: 20px;
		cursor: pointer;
		color: #94a3b8;
	}

	.modal-body {
		padding: 20px;
	}

	.form-group {
		margin-top: 12px;
	}

	.form-group label {
		display: block;
		margin-bottom: 6px;
		font-size: 13px;
		color: #475569;
		font-weight: 500;
	}

	.form-group textarea {
		width: 100%;
		padding: 10px 12px;
		border: 1px solid #cbd5e1;
		border-radius: 8px;
		font-size: 14px;
		font-family: inherit;
		resize: vertical;
		box-sizing: border-box;
	}

	.error-message {
		margin-top: 12px;
		padding: 10px 14px;
		background: #fef2f2;
		color: #dc2626;
		border-radius: 8px;
		font-size: 13px;
		border: 1px solid #fecaca;
	}

	.modal-footer {
		padding: 16px 20px;
		border-top: 1px solid #e2e8f0;
		display: flex;
		justify-content: flex-end;
		gap: 10px;
	}

	.btn {
		padding: 10px 20px;
		border-radius: 8px;
		border: none;
		cursor: pointer;
		font-size: 14px;
		font-weight: 500;
	}

	.btn.primary {
		background: #2563eb;
		color: white;
	}

	.btn.danger {
		background: #ef4444;
		color: white;
	}

	.btn.secondary {
		background: #f1f5f9;
		color: #475569;
	}

	.btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.audit-timeline {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.audit-item {
		display: flex;
		gap: 12px;
		position: relative;
	}

	.audit-item:not(:last-child)::after {
		content: '';
		position: absolute;
		left: 6px;
		top: 20px;
		bottom: -8px;
		width: 2px;
		background: #e2e8f0;
	}

	.audit-dot {
		width: 14px;
		height: 14px;
		border-radius: 50%;
		flex-shrink: 0;
		margin-top: 3px;
		box-shadow: 0 0 0 3px white, 0 0 0 4px #e2e8f0;
	}

	.audit-content {
		flex: 1;
		min-width: 0;
	}

	.audit-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 4px;
	}

	.audit-op {
		font-size: 14px;
		font-weight: 600;
	}

	.audit-operator {
		font-size: 12px;
		color: #64748b;
	}

	.audit-status {
		font-size: 12px;
		color: #64748b;
		margin-bottom: 4px;
		display: flex;
		align-items: center;
		gap: 6px;
	}

	.status-old {
		color: #94a3b8;
	}

	.status-arrow {
		color: #cbd5e1;
	}

	.status-new {
		color: #10b981;
		font-weight: 500;
	}

	.status-same {
		color: #f59e0b;
	}

	.audit-remark {
		font-size: 12px;
		color: #475569;
		background: #f8fafc;
		padding: 6px 10px;
		border-radius: 6px;
		margin-bottom: 4px;
		line-height: 1.5;
	}

	.audit-time {
		font-size: 11px;
		color: #94a3b8;
	}

	.empty-log {
		text-align: center;
		padding: 30px;
		color: #94a3b8;
		font-size: 13px;
	}
</style>

// frontend/pages/applications/[id].vue
<template>
  <div class="application-detail">
    <div class="page-header">
      <div class="header-left">
        <button class="back-btn" @click="goBack">
          ← 返回列表
        </button>
        <h2 class="page-title">展期申请详情</h2>
      </div>
      <div class="header-right">
        <span v-if="application?.is_urgent" class="status-tag status-urgent" style="margin-right: 8px;">紧急</span>
        <span :class="['status-tag', `status-${application?.status}`]">
          {{ statusMap[application?.status || ''] || application?.status }}
        </span>
      </div>
    </div>

    <div class="detail-grid" v-if="application">
      <div class="card section-card">
        <div class="section-title">
          <span class="section-icon">👤</span>
          <h3>借款人信息</h3>
        </div>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">申请编号</span>
            <span class="info-value">{{ application.application_no }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">借款人姓名</span>
            <span class="info-value">{{ application.borrower_name }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">身份证号</span>
            <span class="info-value">{{ application.borrower_id_card }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">联系电话</span>
            <span class="info-value">{{ application.borrower_phone }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">登记员</span>
            <span class="info-value">{{ application.registrar_name }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">申请时间</span>
            <span class="info-value">{{ formatDateTime(application.created_at) }}</span>
          </div>
        </div>
      </div>

      <div class="card section-card">
        <div class="section-title">
          <span class="section-icon">💰</span>
          <h3>借款信息</h3>
        </div>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">借款合同号</span>
            <span class="info-value">{{ application.loan_contract_no }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">原始本金</span>
            <span class="info-value">¥{{ formatNumber(application.original_principal) }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">原利率</span>
            <span class="info-value">{{ application.original_interest_rate }}%</span>
          </div>
          <div class="info-item">
            <span class="info-label">原到期日</span>
            <span class="info-value">{{ application.original_due_date }}</span>
          </div>
        </div>
      </div>

      <div class="card section-card">
        <div class="section-title">
          <span class="section-icon">📝</span>
          <h3>展期信息</h3>
        </div>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">展期天数</span>
            <span class="info-value highlight">{{ application.extension_days }} 天</span>
          </div>
          <div class="info-item">
            <span class="info-label">展期后到期日</span>
            <span class="info-value">{{ application.new_due_date }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">执行利率</span>
            <span class="info-value">{{ application.new_interest_rate || application.original_interest_rate }}%</span>
          </div>
          <div class="info-item">
            <span class="info-label">是否紧急</span>
            <span class="info-value">
              <span v-if="application.is_urgent" class="status-tag status-urgent">是</span>
              <span v-else class="status-tag status-draft">否</span>
            </span>
          </div>
        </div>
        <div class="info-item full-width">
          <span class="info-label">展期原因</span>
          <span class="info-value">{{ application.extension_reason }}</span>
        </div>
      </div>

      <div class="card section-card">
        <div class="section-title">
          <span class="section-icon">👥</span>
          <h3>处理人员</h3>
        </div>
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">登记员</span>
            <span class="info-value">{{ application.registrar_name }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">审核主管</span>
            <span class="info-value">{{ application.reviewer_name || '-' }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">复核负责人</span>
            <span class="info-value">{{ application.final_reviewer_name || '-' }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">当前处理角色</span>
            <span class="info-value">{{ roleMap[application.current_handler_role] || application.current_handler_role || '无' }}</span>
          </div>
        </div>
      </div>

      <div class="card section-card full-width">
        <div class="section-title">
          <span class="section-icon">📅</span>
          <h3>还款计划</h3>
        </div>
        <div class="table-wrapper">
          <table class="table table-small">
            <thead>
              <tr>
                <th>期数</th>
                <th>还款日期</th>
                <th>应还本金</th>
                <th>应还利息</th>
                <th>应还总额</th>
                <th>是否展期</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(item, index) in application.repayment_plans" :key="item.id">
                <td>第 {{ item.plan_no }} 期</td>
                <td>{{ item.due_date }}</td>
                <td>¥{{ formatNumber(item.principal) }}</td>
                <td>¥{{ formatNumber(item.interest) }}</td>
                <td>¥{{ formatNumber(item.total_amount) }}</td>
                <td>
                  <span v-if="item.is_extension_period" class="status-tag status-review_approved">是</span>
                  <span v-else class="status-tag status-draft">否</span>
                </td>
              </tr>
              <tr v-if="application.repayment_plans.length === 0">
                <td colspan="6" class="empty-row">暂无还款计划</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="card section-card full-width">
        <div class="section-title">
          <span class="section-icon">📎</span>
          <h3>材料清单</h3>
        </div>
        <div class="table-wrapper">
          <table class="table table-small">
            <thead>
              <tr>
                <th>材料类型</th>
                <th>材料名称</th>
                <th>是否必填</th>
                <th>核验状态</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in application.materials" :key="item.id">
                <td>{{ item.material_type_display }}</td>
                <td>{{ item.material_name }}</td>
                <td>
                  <span v-if="item.is_required" class="status-tag status-urgent">必填</span>
                  <span v-else class="status-tag status-draft">选填</span>
                </td>
                <td>
                  <span v-if="item.is_verified" class="status-tag status-final_approved">已核验</span>
                  <span v-else class="status-tag status-draft">未核验</span>
                </td>
              </tr>
              <tr v-if="application.materials.length === 0">
                <td colspan="4" class="empty-row">暂无材料</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="card section-card full-width" v-if="application.review_opinion || application.final_review_opinion">
        <div class="section-title">
          <span class="section-icon">💬</span>
          <h3>审核意见</h3>
        </div>
        <div class="comment-list">
          <div v-if="application.review_opinion" class="comment-item">
            <div class="comment-header">
              <span class="comment-user">{{ application.reviewer_name }}</span>
              <span class="comment-role">展期审核主管</span>
              <span :class="['status-tag', `status-${application.status}`]">审核</span>
            </div>
            <div class="comment-content">{{ application.review_opinion }}</div>
          </div>
          <div v-if="application.final_review_opinion" class="comment-item">
            <div class="comment-header">
              <span class="comment-user">{{ application.final_reviewer_name }}</span>
              <span class="comment-role">小贷公司复核负责人</span>
              <span class="status-tag status-final_approved">复核</span>
            </div>
            <div class="comment-content">{{ application.final_review_opinion }}</div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="loading" class="loading-card">
      <p>加载中...</p>
    </div>

    <div class="card timeline-card" v-if="!loading">
      <div class="section-title">
        <span class="section-icon">⏱️</span>
        <h3>审计日志</h3>
      </div>
      <div class="timeline">
        <div v-for="(log, index) in auditLogs" :key="log.id" class="timeline-item">
          <div class="timeline-dot"></div>
          <div class="timeline-content">
            <div class="timeline-header">
              <span class="timeline-title">{{ log.action_display }}</span>
              <span class="timeline-time">{{ formatDateTime(log.created_at) }}</span>
            </div>
            <div class="timeline-desc">{{ log.action_detail || log.remark || '-' }}</div>
            <div class="timeline-meta">
              <span>操作人：{{ log.operator_name }}</span>
              <span v-if="log.old_status">原状态：{{ statusMap[log.old_status] || log.old_status }}</span>
              <span v-if="log.new_status">新状态：{{ statusMap[log.new_status] || log.new_status }}</span>
            </div>
          </div>
        </div>
        <div v-if="auditLogs.length === 0 && !auditLoading" class="empty-timeline">
          暂无审计日志
        </div>
      </div>
    </div>

    <div class="action-bar" v-if="showActionBar">
      <button class="btn btn-secondary" @click="goBack">返回</button>
      <div class="action-btns">
        <template v-if="isRegistrar && canSubmitStatus">
          <button class="btn btn-primary" @click="handleSubmit" :disabled="submitting">
            {{ submitting ? '提交中...' : '提交申请' }}
          </button>
        </template>
        <template v-if="isReviewer && application?.status === 'pending_review'">
          <button class="btn btn-reject" @click="openReviewModal('reject')">审核退回</button>
          <button class="btn btn-primary" @click="openReviewModal('approve')">审核通过</button>
        </template>
        <template v-if="isFinalReviewer && application?.status === 'review_approved'">
          <button class="btn btn-reject" @click="openFinalModal('reject')">复核拒绝</button>
          <button class="btn btn-primary" @click="openFinalModal('approve')">复核通过</button>
        </template>
        <template v-if="isFinalReviewer && application?.status === 'final_approved'">
          <button class="btn btn-primary" @click="handleArchive" :disabled="submitting">
            {{ submitting ? '归档中...' : '归档' }}
          </button>
        </template>
      </div>
    </div>

    <div v-if="showReviewModal" class="modal-overlay" @click.self="showReviewModal = false">
      <div class="modal">
        <div class="modal-header">
          <h3>{{ reviewAction === 'approve' ? '审核通过' : '审核退回' }}</h3>
          <button class="modal-close" @click="showReviewModal = false">×</button>
        </div>
        <div class="modal-body">
          <label class="form-label">审核意见</label>
          <textarea v-model="reviewComment" class="form-textarea" placeholder="请输入审核意见..." rows="4"></textarea>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" @click="showReviewModal = false">取消</button>
          <button :class="['btn', reviewAction === 'approve' ? 'btn-primary' : 'btn-reject']" @click="handleReview" :disabled="submitting">
            {{ submitting ? '提交中...' : '确认' }}
          </button>
        </div>
      </div>
    </div>

    <div v-if="showFinalModal" class="modal-overlay" @click.self="showFinalModal = false">
      <div class="modal">
        <div class="modal-header">
          <h3>{{ finalAction === 'approve' ? '复核通过' : '复核拒绝' }}</h3>
          <button class="modal-close" @click="showFinalModal = false">×</button>
        </div>
        <div class="modal-body">
          <label class="form-label">复核意见</label>
          <textarea v-model="finalComment" class="form-textarea" placeholder="请输入复核意见..." rows="4"></textarea>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" @click="showFinalModal = false">取消</button>
          <button :class="['btn', finalAction === 'approve' ? 'btn-primary' : 'btn-reject']" @click="handleFinalReview" :disabled="submitting">
            {{ submitting ? '提交中...' : '确认' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'default'
})

const { get, post, put } = useApi()
const userStore = useUserStore()
const route = useRoute()

const id = computed(() => route.params.id as string)

interface RepaymentPlan {
  id: number
  plan_no: number
  due_date: string
  principal: string
  interest: string
  total_amount: string
  is_extension_period: boolean
}

interface Material {
  id: number
  material_type: string
  material_type_display: string
  material_name: string
  is_required: boolean
  is_verified: boolean
  upload_time: string
}

interface ApplicationDetail {
  id: number
  application_no: string
  qr_code: string
  borrower_name: string
  borrower_id_card: string
  borrower_phone: string
  loan_contract_no: string
  original_principal: string
  original_interest_rate: string
  original_due_date: string
  extension_days: number
  extension_reason: string
  new_due_date: string
  new_interest_rate: string | null
  status: string
  status_display: string
  current_handler_role: string
  registrar_name: string
  reviewer_name: string | null
  final_reviewer_name: string | null
  review_opinion: string
  final_review_opinion: string
  is_urgent: boolean
  deadline: string | null
  created_at: string
  updated_at: string
  version: number
  repayment_plans: RepaymentPlan[]
  materials: Material[]
}

interface AuditLog {
  id: number
  application_no: string
  operator_name: string
  action: string
  action_display: string
  action_detail: string
  old_status: string
  new_status: string
  remark: string
  created_at: string
}

const loading = ref(false)
const auditLoading = ref(false)
const submitting = ref(false)
const application = ref<ApplicationDetail | null>(null)
const auditLogs = ref<AuditLog[]>([])

const showReviewModal = ref(false)
const reviewAction = ref<'approve' | 'reject'>('approve')
const reviewComment = ref('')

const showFinalModal = ref(false)
const finalAction = ref<'approve' | 'reject'>('approve')
const finalComment = ref('')

const isRegistrar = computed(() => userStore.hasRole('registrar'))
const isReviewer = computed(() => userStore.hasRole('reviewer'))
const isFinalReviewer = computed(() => userStore.hasRole('final_reviewer'))

const canSubmitStatus = computed(() => {
  return application.value?.status === 'draft' || application.value?.status === 'returned_for_correction'
})

const showActionBar = computed(() => {
  if (!application.value) return false
  if (isRegistrar.value && canSubmitStatus.value) return true
  if (isReviewer.value && application.value.status === 'pending_review') return true
  if (isFinalReviewer.value && application.value.status === 'review_approved') return true
  if (isFinalReviewer.value && application.value.status === 'final_approved') return true
  return false
})

const statusMap: Record<string, string> = {
  draft: '草稿',
  pending_review: '待审核',
  review_approved: '审核通过待复核',
  returned_for_correction: '退回补正',
  final_approved: '复核通过待归档',
  rejected: '已拒绝',
  archived: '已归档'
}

const roleMap: Record<string, string> = {
  registrar: '展期登记员',
  reviewer: '展期审核主管',
  final_reviewer: '小贷公司复核负责人',
  admin: '系统管理员'
}

const formatDateTime = (dateStr: string): string => {
  if (!dateStr) return ''
  const date = new Date(dateStr)
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  const hours = String(date.getHours()).padStart(2, '0')
  const minutes = String(date.getMinutes()).padStart(2, '0')
  return `${year}-${month}-${day} ${hours}:${minutes}`
}

const formatNumber = (num: string | number): string => {
  if (num === undefined || num === null) return '0'
  const n = typeof num === 'string' ? parseFloat(num) : num
  return n.toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

const loadDetail = async () => {
  loading.value = true
  try {
    const data = await get<ApplicationDetail>(`/applications/${id.value}`)
    application.value = data
  } catch (error: any) {
    console.error('Failed to load application detail:', error)
    alert(error.message || '加载失败')
  } finally {
    loading.value = false
  }
}

const loadAuditLogs = async () => {
  if (!application.value?.application_no) return
  auditLoading.value = true
  try {
    const data = await get<{ items: AuditLog[]; total: number }>('/audit-logs', {
      application_no: application.value.application_no,
      page_size: 50
    })
    auditLogs.value = data.items || []
  } catch (error) {
    console.error('Failed to load audit logs:', error)
  } finally {
    auditLoading.value = false
  }
}

const handleSubmit = async () => {
  if (!confirm('确定提交该申请？提交后将进入审核流程。')) return
  submitting.value = true
  try {
    await put(`/applications/${id.value}/submit`)
    alert('提交成功')
    await loadDetail()
    await loadAuditLogs()
  } catch (error: any) {
    alert(error.message || '提交失败')
  } finally {
    submitting.value = false
  }
}

const openReviewModal = (action: 'approve' | 'reject') => {
  reviewAction.value = action
  reviewComment.value = ''
  showReviewModal.value = true
}

const handleReview = async () => {
  if (!reviewComment.value.trim()) {
    alert('请输入审核意见')
    return
  }
  submitting.value = true
  try {
    await post(`/applications/${id.value}/review`, {
      application_id: Number(id.value),
      approved: reviewAction.value === 'approve',
      opinion: reviewComment.value
    })
    alert('操作成功')
    showReviewModal.value = false
    reviewComment.value = ''
    await loadDetail()
    await loadAuditLogs()
  } catch (error: any) {
    alert(error.message || '操作失败')
  } finally {
    submitting.value = false
  }
}

const openFinalModal = (action: 'approve' | 'reject') => {
  finalAction.value = action
  finalComment.value = ''
  showFinalModal.value = true
}

const handleFinalReview = async () => {
  if (!finalComment.value.trim()) {
    alert('请输入复核意见')
    return
  }
  submitting.value = true
  try {
    await post(`/applications/${id.value}/final-review`, {
      application_id: Number(id.value),
      approved: finalAction.value === 'approve',
      opinion: finalComment.value
    })
    alert('操作成功')
    showFinalModal.value = false
    finalComment.value = ''
    await loadDetail()
    await loadAuditLogs()
  } catch (error: any) {
    alert(error.message || '操作失败')
  } finally {
    submitting.value = false
  }
}

const handleArchive = async () => {
  if (!confirm('确定归档该申请？归档后不可修改。')) return
  submitting.value = true
  try {
    await put(`/applications/${id.value}/archive`)
    alert('归档成功')
    await loadDetail()
    await loadAuditLogs()
  } catch (error: any) {
    alert(error.message || '归档失败')
  } finally {
    submitting.value = false
  }
}

const goBack = () => {
  navigateTo('/applications')
}

onMounted(() => {
  loadDetail()
  loadAuditLogs()
})
</script>

<style scoped>
.application-detail {
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding-bottom: 80px;
}

.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 16px;
}

.back-btn {
  background: none;
  border: none;
  color: #3b82f6;
  cursor: pointer;
  font-size: 14px;
  padding: 0;
}

.back-btn:hover {
  text-decoration: underline;
}

.page-title {
  font-size: 20px;
  font-weight: 600;
  color: #1f2937;
  margin: 0;
}

.detail-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 20px;
}

.section-card {
  padding: 20px;
}

.section-card.full-width {
  grid-column: 1 / -1;
}

.section-title {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid #f3f4f6;
}

.section-icon {
  font-size: 20px;
}

.section-title h3 {
  font-size: 16px;
  font-weight: 600;
  color: #1f2937;
  margin: 0;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.info-item.full-width {
  grid-column: 1 / -1;
}

.info-label {
  font-size: 12px;
  color: #6b7280;
}

.info-value {
  font-size: 14px;
  color: #1f2937;
  font-weight: 500;
}

.info-value.highlight {
  color: #3b82f6;
  font-size: 16px;
}

.table-wrapper {
  overflow-x: auto;
}

.table-small th,
.table-small td {
  padding: 8px 12px;
  font-size: 13px;
}

.empty-row {
  text-align: center;
  color: #9ca3af;
  padding: 30px 0 !important;
}

.loading-card {
  background: #fff;
  border-radius: 12px;
  padding: 40px;
  text-align: center;
  color: #6b7280;
}

.comment-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.comment-item {
  padding: 16px;
  background: #f9fafb;
  border-radius: 8px;
}

.comment-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 8px;
}

.comment-user {
  font-size: 14px;
  font-weight: 600;
  color: #1f2937;
}

.comment-role {
  font-size: 12px;
  color: #6b7280;
}

.comment-content {
  font-size: 13px;
  color: #374151;
  line-height: 1.6;
}

.timeline-card {
  padding: 20px;
}

.timeline {
  position: relative;
  padding-left: 30px;
}

.timeline-item {
  position: relative;
  padding-bottom: 24px;
}

.timeline-item:last-child {
  padding-bottom: 0;
}

.timeline-dot {
  position: absolute;
  left: -30px;
  top: 4px;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #3b82f6;
  border: 2px solid #fff;
  box-shadow: 0 0 0 2px #3b82f6;
}

.timeline-content {
  padding-left: 8px;
}

.timeline-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 4px;
}

.timeline-title {
  font-size: 14px;
  font-weight: 600;
  color: #1f2937;
}

.timeline-time {
  font-size: 12px;
  color: #9ca3af;
}

.timeline-desc {
  font-size: 13px;
  color: #6b7280;
  margin-bottom: 4px;
}

.timeline-meta {
  display: flex;
  gap: 16px;
  font-size: 12px;
  color: #9ca3af;
}

.empty-timeline {
  text-align: center;
  color: #9ca3af;
  padding: 30px 0;
}

.action-bar {
  position: fixed;
  bottom: 0;
  left: 240px;
  right: 0;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;
  background: #fff;
  border-top: 1px solid #e5e7eb;
  box-shadow: 0 -2px 10px rgba(0, 0, 0, 0.05);
  z-index: 100;
}

.action-btns {
  display: flex;
  gap: 12px;
}

.btn-reject {
  background: #fff;
  color: #ef4444;
  border: 1px solid #fecaca;
}

.btn-reject:hover {
  background: #fef2f2;
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal {
  background: #fff;
  border-radius: 12px;
  width: 500px;
  max-width: 90%;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px;
  border-bottom: 1px solid #f3f4f6;
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1f2937;
}

.modal-close {
  background: none;
  border: none;
  font-size: 24px;
  color: #9ca3af;
  cursor: pointer;
  line-height: 1;
}

.modal-close:hover {
  color: #6b7280;
}

.modal-body {
  padding: 20px;
}

.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 16px 20px;
  border-top: 1px solid #f3f4f6;
}

.form-label {
  display: block;
  font-size: 13px;
  font-weight: 500;
  color: #374151;
  margin-bottom: 8px;
}

.form-textarea {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 14px;
  font-family: inherit;
  outline: none;
  resize: vertical;
  transition: all 0.2s;
}

.form-textarea:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.status-urgent {
  background: #fee2e2;
  color: #991b1b;
}

@media (max-width: 768px) {
  .detail-grid {
    grid-template-columns: 1fr;
  }

  .action-bar {
    left: 0;
  }
}
</style>
